__author__ = 'YangZiyue, ShanYongtao'
__author_email__ = 'yangzy58@mail2.sysu.edu.cn'
__description__ = 'A one-stop software solution for RNA virus mining and host-association prediction.'
__license__ = 'MIT'
__name__ = 'phyrvm'
__python_requires__ = '==3.8'
__status__ = 'Production'
__title__ = 'Phyrvm'
__url__ = 'https://github.com/ZiyueYang01/Phyrvm'
__version__ = '3.1.0'
